"""Block registry — discovers and loads pre-built transformation blocks."""

from __future__ import annotations

import logging
from pathlib import Path

from src.blocks.base import Block
from src.schema.models import UnifiedSchema
from src.blocks.strip_whitespace import StripWhitespaceBlock
from src.blocks.lowercase_brand import LowercaseBrandBlock
from src.blocks.remove_noise_words import RemoveNoiseWordsBlock
from src.blocks.strip_punctuation import StripPunctuationBlock
from src.blocks.extract_quantity_column import ExtractQuantityColumnBlock
from src.blocks.keep_quantity_in_name import KeepQuantityInNameBlock
from src.blocks.extract_allergens import ExtractAllergensBlock
from src.blocks.fuzzy_deduplicate import FuzzyDeduplicateBlock
from src.blocks.column_wise_merge import ColumnWiseMergeBlock
from src.blocks.golden_record_select import GoldenRecordSelectBlock
from src.blocks.dq_score import DQScorePreBlock, DQScorePostBlock
from src.blocks.llm_enrich import LLMEnrichBlock
from src.blocks.schema_enforce import SchemaEnforceBlock

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
GENERATED_BLOCKS_DIR = PROJECT_ROOT / "src" / "blocks" / "generated"

# All registered block instances
_BLOCKS: dict[str, Block] = {
    "strip_whitespace": StripWhitespaceBlock(),
    "lowercase_brand": LowercaseBrandBlock(),
    "remove_noise_words": RemoveNoiseWordsBlock(),
    "strip_punctuation": StripPunctuationBlock(),
    "extract_quantity_column": ExtractQuantityColumnBlock(),
    "keep_quantity_in_name": KeepQuantityInNameBlock(),
    "extract_allergens": ExtractAllergensBlock(),
    "fuzzy_deduplicate": FuzzyDeduplicateBlock(),
    "column_wise_merge": ColumnWiseMergeBlock(),
    "golden_record_select": GoldenRecordSelectBlock(),
    "dq_score_pre": DQScorePreBlock(),
    "dq_score_post": DQScorePostBlock(),
    "llm_enrich": LLMEnrichBlock(),
    "schema_enforce": SchemaEnforceBlock(),
}

# Stage definitions: stage_name -> list of constituent blocks
_STAGES: dict[str, list[str]] = {
    "dedup_stage": ["fuzzy_deduplicate", "column_wise_merge", "golden_record_select"],
    "enrich_stage": ["extract_allergens", "llm_enrich"],
}


def _discover_generated_blocks() -> dict[str, Block]:
    """Discover and load dynamically generated blocks from src/blocks/generated/."""
    generated = {}

    if not GENERATED_BLOCKS_DIR.exists():
        GENERATED_BLOCKS_DIR.mkdir(parents=True, exist_ok=True)
        logger.info(f"Created generated blocks directory: {GENERATED_BLOCKS_DIR}")
        return generated

    for domain_dir in GENERATED_BLOCKS_DIR.iterdir():
        if not domain_dir.is_dir():
            continue

        domain = domain_dir.name

        # Discover YAML-based DynamicMappingBlocks (only YAML files are used now)
        for yaml_file in domain_dir.glob("DYNAMIC_MAPPING_*.yaml"):
            try:
                from src.blocks.dynamic_mapping import DynamicMappingBlock

                block = DynamicMappingBlock(domain=domain, yaml_path=str(yaml_file))
                generated[block.name] = block
                logger.info(
                    f"Loaded YAML mapping block: {block.name} "
                    f"(domain: {domain}, file: {yaml_file.name})"
                )
            except Exception as e:
                logger.error(f"Failed to load YAML mapping from {yaml_file}: {e}")

    return generated


class BlockRegistry:
    """Registry of pre-built and dynamically generated transformation blocks."""

    _instance: "BlockRegistry | None" = None

    @classmethod
    def instance(cls) -> "BlockRegistry":
        """Return the singleton registry, creating it on first call."""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    @classmethod
    def reset(cls) -> None:
        """Clear the singleton (for testing only)."""
        cls._instance = None

    def __init__(self) -> None:
        self.blocks = dict(_BLOCKS)
        self._load_generated_blocks()

    def _load_generated_blocks(self) -> None:
        """Load dynamically generated blocks from disk."""
        generated = _discover_generated_blocks()
        self.blocks.update(generated)
        logger.info(
            f"BlockRegistry initialized with {len(self.blocks)} blocks "
            f"({len(generated)} generated)"
        )

    def refresh(self) -> None:
        """Re-discover generated blocks (call after register_blocks_node writes new files)."""
        self._load_generated_blocks()

    def register_block(self, block: Block) -> None:
        """Register a new block (e.g., generated by Agent 2)."""
        self.blocks[block.name] = block
        logger.info(f"Registered block: {block.name}")

    def get(self, name: str) -> Block:
        """Get a block by name. Raises KeyError if not found."""
        if name not in self.blocks:
            raise KeyError(
                f"Block '{name}' not found. Available: {list(self.blocks.keys())}"
            )
        return self.blocks[name]

    def is_stage(self, name: str) -> bool:
        """Check if name is a stage (composite block)."""
        return name in _STAGES

    def expand_stage(self, name: str) -> list[str]:
        """Expand a stage to its constituent blocks."""
        return _STAGES.get(name, [name])

    def list_blocks(self, domain: str | None = None) -> list[str]:
        """List available block names, optionally filtered by domain."""
        if domain is None:
            return list(self.blocks.keys())
        return [
            name
            for name, block in self.blocks.items()
            if block.domain in ("all", domain)
        ]

    def get_default_sequence(
        self,
        domain: str = "nutrition",
        unified_schema: UnifiedSchema | None = None,
        enable_enrichment: bool = True,
    ) -> list[str]:
        """
        Return the default block execution sequence for a domain.

        Uses stages for dedup and enrichment to make sequence more readable.
        The __generated__ sentinel marks where agent-generated transforms are injected.
        """
        base = [
            "dq_score_pre",
            "__generated__",
            "strip_whitespace",
            "lowercase_brand",
            "remove_noise_words",
            "strip_punctuation",
        ]

        if domain == "pricing":
            base.append("keep_quantity_in_name")
        else:
            base.append("extract_quantity_column")

        has_enrichment = (
            bool(unified_schema.enrichment_columns)
            if unified_schema is not None
            else domain in ("nutrition", "safety")
        )

        base.append("dedup_stage")

        if has_enrichment and enable_enrichment:
            base.append("enrich_stage")

        base.append("dq_score_post")
        return base

    def get_silver_sequence(self, domain: str = "nutrition") -> list[str]:
        """
        Block sequence for Bronze→Silver: schema transform only.
        Stops before dedup and enrichment — Silver contains all rows.
        """
        base = [
            "dq_score_pre",
            "__generated__",
            "strip_whitespace",
            "lowercase_brand",
            "remove_noise_words",
            "strip_punctuation",
        ]
        if domain == "pricing":
            base.append("keep_quantity_in_name")
        else:
            base.append("extract_quantity_column")
        base.append("schema_enforce")
        return base

    def get_gold_sequence(self, domain: str = "nutrition") -> list[str]:
        """
        Block sequence for Silver→Gold: dedup + enrichment + final DQ score.
        Reads Silver Parquet (already schema-transformed).
        """
        base = ["dedup_stage"]
        if domain in ("nutrition", "safety", "retail"):
            base.append("enrich_stage")
        base.append("dq_score_post")
        return base

    def get_blocks_with_metadata(self, block_names: list[str]) -> list[dict]:
        """Return metadata dicts for the given block names (preserving order).

        Handles stages by returning constituent block metadata.
        """
        result = []
        for name in block_names:
            if name == "__generated__":
                result.append(
                    {
                        "name": "__generated__",
                        "description": "Injection point for agent-generated transform blocks. MUST run after dq_score_pre and before normalization blocks.",
                        "inputs": ["source columns requiring schema transformation"],
                        "outputs": ["unified schema target columns"],
                    }
                )
                continue

            if self.is_stage(name):
                constituent_blocks = self.expand_stage(name)
                for block_name in constituent_blocks:
                    block = self.blocks.get(block_name)
                    if block:
                        result.append(
                            {
                                "name": block_name,
                                "description": f"[{name}] {block.description}",
                                "inputs": block.inputs,
                                "outputs": block.outputs,
                            }
                        )
                continue

            block = self.blocks.get(name)
            if block:
                result.append(
                    {
                        "name": name,
                        "description": block.description,
                        "inputs": block.inputs,
                        "outputs": block.outputs,
                    }
                )
        return result
