"""LangGraph state schema for the ETL pipeline graph."""

from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict


class GapItem(TypedDict):
    """A single schema gap between source and unified schema."""

    target_column: str
    target_type: str
    source_column: Optional[str]  # None if column must be derived
    source_type: Optional[str]
    action: str  # MAP, DROP, NEW, ADD
    sample_values: list[str]


class GeneratedBlock(TypedDict):
    """A block generated by Agent 2 for schema transformation."""

    block_name: str
    block_code: str
    file_path: Optional[str]  # set by register_blocks_node; None until written to disk
    target_column: str
    source_column: Optional[str]
    gap_type: str  # TYPE_CONVERSION, COLUMN_RENAME, COLUMN_DROP, COLUMN_CREATE, FORMAT_TRANSFORM
    validation_passed: bool
    validation_error: Optional[str]


class PipelineState(TypedDict, total=False):
    """
    Full state flowing through the LangGraph pipeline.

    total=False allows nodes to set fields incrementally —
    not every field is present at every node.
    """

    # Input
    source_path: str
    source_df: Any  # pd.DataFrame — not JSON-serializable, in-memory only
    source_schema: dict  # column_name -> {dtype, null_rate, sample_values}
    domain: str  # "nutrition", "safety", "pricing"
    enable_enrichment: bool  # user toggle — False skips allergen + llm_enrich blocks

    # Schema analysis (set by orchestrator node)
    unified_schema: dict
    unified_schema_existed: bool  # True if schema was loaded, False if derived
    gaps: list[GapItem]
    column_mapping: dict  # source_col -> unified_col
    enrichment_columns_to_generate: list[str]  # enrichment cols absent from source
    mapping_warnings: list[str]  # required unified cols not covered by mapping

    # Registry results (set by registry_check node)
    block_registry_hits: dict  # target_col -> block_name
    registry_misses: list[GapItem]

    # Code generation results (set by code_generator node)
    generated_blocks: list[GeneratedBlock]
    retry_count: int
    max_retries: int

    # Pipeline execution
    block_sequence: list[str]
    sequence_reasoning: str  # Agent 3's rationale for the chosen sequence
    working_df: Any  # pd.DataFrame
    dq_score_pre: float
    dq_score_post: float

    # Enrichment
    enrichment_stats: dict  # tier -> row_count

    # Quarantine
    quarantined_df: Any  # pd.DataFrame — rows that failed post-enrichment validation
    quarantine_reasons: list[dict]  # [{row_idx, missing_fields, reason}]

    # Audit
    audit_log: list[dict]
    errors: list[str]
