"""Pydantic models for the unified schema configuration."""

from __future__ import annotations

import json
from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


class ColumnSpec(BaseModel):
    type: Literal["string", "float", "integer", "boolean"]
    required: bool = False
    enrichment: bool = False
    computed: bool = False
    enrichment_alias: Optional[str] = None
    # extra=allow: tolerate future flags added to the JSON without breaking validation
    model_config = {"extra": "allow"}


class DQWeights(BaseModel):
    completeness: float = 0.4
    freshness: float = 0.35
    ingredient_richness: float = 0.25
    model_config = {"extra": "allow"}

    @model_validator(mode="after")
    def _weights_sum_to_one(self) -> "DQWeights":
        total = self.completeness + self.freshness + self.ingredient_richness
        if abs(total - 1.0) > 1e-6:
            raise ValueError(f"DQ weights must sum to 1.0, got {total:.4f}")
        return self


class UnifiedSchema(BaseModel):
    columns: dict[str, ColumnSpec]
    dq_weights: DQWeights = Field(default_factory=DQWeights)

    @property
    def mappable_columns(self) -> dict[str, ColumnSpec]:
        """Columns requiring source data — excludes computed and enrichment-only cols."""
        return {k: v for k, v in self.columns.items() if not v.computed and not v.enrichment}

    @property
    def required_columns(self) -> set[str]:
        """Names of required, non-computed columns."""
        return {k for k, v in self.columns.items() if v.required and not v.computed}

    @property
    def enrichment_columns(self) -> dict[str, ColumnSpec]:
        """Columns generated by enrichment blocks, not present in source data."""
        return {k: v for k, v in self.columns.items() if v.enrichment}

    def for_prompt(self) -> dict:
        """Schema dict for LLM prompt injection — excludes computed columns.

        Returns a plain dict so it is directly usable with json.dumps().
        """
        return {
            "columns": {
                k: v.model_dump(exclude_none=True)
                for k, v in self.columns.items()
                if not v.computed
            }
        }

    def to_json(self, **kwargs) -> str:
        """Serialize to JSON string (for saving to disk)."""
        return json.dumps(self.model_dump(), **kwargs)
